import 'package:flutter/material.dart';
import '../services/farm_service.dart';
class FarmsScreen extends StatefulWidget { const FarmsScreen({super.key}); @override State<FarmsScreen> createState()=>_FarmsScreenState(); }
class _FarmsScreenState extends State<FarmsScreen>{
 final service=FarmService(); final name=TextEditingController(),area=TextEditingController(),location=TextEditingController(),soil=TextEditingController(); bool loading=false;
 @override void dispose(){name.dispose();area.dispose();location.dispose();soil.dispose();super.dispose();}
 Future<void> refresh()async{setState((){});}
 Future<void> addFarm()async{final a=double.tryParse(area.text);if(name.text.trim().length<2||a==null||a<=0){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enter a valid farm name and area.')));return;}setState(()=>loading=true);final ok=await service.createFarm(name.text.trim(),a,location.text.trim(),soil.text.trim());if(!mounted)return;setState(()=>loading=false);if(ok){name.clear();area.clear();location.clear();soil.clear();setState((){});}ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'Farm added':'Could not add farm')));}
 Future<void> deleteFarm(String id)async{final ok=await service.deleteFarm(id);if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(ok?'Farm deleted':'Could not delete farm')));setState((){});}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('My Farms')),body:FutureBuilder<List<Map<String,dynamic>>>(future:service.listFarms(),builder:(context,snapshot){if(snapshot.connectionState==ConnectionState.waiting)return const Center(child:CircularProgressIndicator());if(snapshot.hasError)return RefreshIndicator(onRefresh:refresh,child:ListView(children:[SizedBox(height:300,child:Center(child:Text(snapshot.error.toString())))]));final farms=snapshot.data??[];return RefreshIndicator(onRefresh:refresh,child:ListView(padding:const EdgeInsets.all(16),children:[if(farms.isEmpty)const Padding(padding:EdgeInsets.all(20),child:Center(child:Text('No farms yet. Add your first farm below.'))),...farms.map((f)=>Card(child:ListTile(leading:const Icon(Icons.agriculture),title:Text(f['name']??''),subtitle:Text(f['area_acres'].toString()+' acres • '+(f['location']??'Location not set').toString()+' • '+(f['soil_type']??'Soil not set').toString()),trailing:IconButton(icon:const Icon(Icons.delete_outline),onPressed:()=>deleteFarm(f['id'].toString()))))),const SizedBox(height:16),Text('Add Farm',style:Theme.of(context).textTheme.titleLarge),const SizedBox(height:12),TextField(controller:name,decoration:const InputDecoration(labelText:'Farm name',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:area,keyboardType:const TextInputType.numberWithOptions(decimal:true),decoration:const InputDecoration(labelText:'Area (acres)',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:location,decoration:const InputDecoration(labelText:'Location',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:soil,decoration:const InputDecoration(labelText:'Soil type',border:OutlineInputBorder())),const SizedBox(height:12),FilledButton(onPressed:loading?null:addFarm,child:Text(loading?'Saving...':'Save Farm'))]));}));
}